### ISSUE TITLE
Google authentication fails with 'java.lang.UnsupportedClassVersionError: com/mxgraph/online/GoogleAuthServlet'

### ISSUE THREAD

**Issue by dq-dd** [jgraph/docker-drawio#86]
env is k3d on Docker Desktop for Mac, testing [this PR](https://github.com/jgraph/docker-drawio/pull/85)

* 20.0.4 fails
* 20.0.3 fails
* 20.0.2 fails
* 20.0.1 **works**
* 19.0.3 **works**

logs/localhost.$DATE.log from 20.0.4 after clicking 'Authorize'
```
12-Jul-2022 00:00:00.654 INFO [http-nio-8080-exec-10] org.apache.catalina.core.ApplicationContext.log Marking servlet [GoogleAuthServlet] as unavailable
12-Jul-2022 00:00:00.655 SEVERE [http-nio-8080-exec-10] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [GoogleAuthServlet]
	java.lang.UnsupportedClassVersionError: com/mxgraph/online/GoogleAuthServlet has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 (unable to load class [com.mxgraph.online.GoogleAuthServlet])
		at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2515)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:877)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1413)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1257)
		at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:535)
		at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:516)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1071)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:789)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:128)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:356)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:867)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1760)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
```

**Comment by davidjgraph** [comment]
20.1.0 will fix this.
